name: Formatting check on pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    environment: 
      name: testing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always
      shell: bash
