name: Formatting check on pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    environment: 
      name: testing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: pre-commit
    - run: python -m pip install pre-commit
      shell: bash
    - run: python -m pip freeze --local
      shell: bash
    - run: pre-commit run --show-diff-on-failure --color=always 
      shell: bash
