name: Testing on pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetches all commits

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          py:
            **/*.py


    - name: Build and Run Docker Compose
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_AUTOTEST_TOKEN }}
      run: |
        docker-compose -f docker-compose.dev.yml up -d 

    - name: Check Docker logs for errors
      run: |
        # Sleep for 10 seconds to let the container initialize
        sleep 10
        logs=$(docker logs wachter-dev)
        if echo $logs | grep -i "exited with code"; then
          echo "Found errors in Docker logs"
          exit 1
        fi

    - name: Run pre-commit on Changed Files
      run: |

        # Execute black inside container
          set -x
          docker exec wachter-dev bash -c "pipenv run black ${{ steps.changed-files.py__changed_files }}"
